export const FETCH_USERS = "FETCH_USERS";
export const FETCH_FEATURES = "FETCH_FEATURES";
export const FETCH_REALTORS = "FETCH_REALTORS";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCH_HOMES = "FETCH_HOMES";
export const FETCH_GALLERY = "FETCH_GALLERY";
